services:
  - type: web
    name: boletim-noticias-agricolas
    env: python
    autoDeploy: true
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TZ
        value: America/Sao_Paulo
